### ISSUE TITLE
 TOCSS: failed to transform "style.main.scss"

### ISSUE THREAD

**Issue by Gctucci** [gethugothemes/bookworm-light#13]
Hello!

I'm just starting in Hugo and found this amazing theme!

However, I can't seem to get it working. I'm following the [official Hugo tutorial](https://gohugo.io/getting-started/quick-start/) to download the Bookwork-light theme as a git submodule inside the themes folder. However, when I execute the server (hugo server) command, I get the following error:
`Error: Error building site: TOCSS: failed to transform "style.main.scss" (text/x-scss): SCSS processing failed: file "C:\...\bookworm-light/assets/scss/_typography.scss", line 4, col 15: Undefined variable: "$h1".`

I'm using Hugo extended version on Win10 (hugo v0.92.1-85E2E862+extended windows/amd64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio), and this bug do not happen with other themes. What am I doing wrong?

**Comment by Gctucci** [comment]
Just realized what I needed to do: the default theme options are not loaded for new projects. I had to copy the Example site config.toml to my own project.

**Comment by nataliepjlin** [comment]
@Gctucci Hi! I recently started in Hugo and meet the same issue. I'm not sure how to make this run the Example site config.toml on my own project. I copied the contents of the `config.toml` in exampleSite, but when I run `hugo server`, it says that it can't find the image file(such as logos). Could you provide the file how you use this theme in your own project? I'm really stuck on  how to arrange all these files...
