### ISSUE TITLE
Error 404: can't deploy on gh-pages

### ISSUE THREAD

**Issue by nataliepjlin** [gethugothemes/bookworm-light#15]
my repo: https://github.com/nataliepjlin/wormtest.git
it works perfectly fine on localhost, but I can't deploy it on gh-pages. Is there any way I can fix this issue?

**Comment by mehedi-sharif** [comment]
Hello @nataliepjlin 

I can see that your website is deployed here:  https://nataliepjlin.github.io/wormtest/

**Comment by nataliepjlin** [comment]
@mehedi-sharif sorry I forgot to close with comment, the problem is solved.
