### ISSUE TITLE
Netlify doesn't display images

### ISSUE THREAD

**Issue by nataliepjlin** [gethugothemes/bookworm-light#16]
web url: https://nataliepjlin.netlify.app/
I've upload the images in the `media` section on Forestry, but Netlify doesn't display images.
I'm not sure is it the right place to upload images on Forestry, do I have to change the path or the directory?
![image](https://user-images.githubusercontent.com/100992247/158374190-8d2f797b-0b7c-4ac2-aa8a-618706f65558.png)
![image](https://user-images.githubusercontent.com/100992247/158373713-0d72e34e-f71f-4f39-8bd7-e32b9eb7aa1a.png)

**Comment by mehedi-sharif** [comment]
Hello @nataliepjlin 

Image folder should be in the `assets` folder, not `asset` folder.
