### ISSUE TITLE
Move "About" to home page?

### ISSUE THREAD

**Issue by nataliepjlin** [gethugothemes/bookworm-light#17]
Hi! I recently start using this amazing theme. Is it possible to set a block for "about" above latest posts? Thanks a lot!

**Comment by tfsomrat** [comment]
Hello @nataliepjlin 

Thanks for using our themes. I am sorry to say that, there is no such feature available in this theme. but everything is possible if you know some development tweaks. There is a premium version of this theme, which has a lot of features. you can try this one, and we also provide a theme customization service [paid]. If you need any customization, then you can contact us at mehedi@themefisher.com. thank you.
