### ISSUE TITLE
Categories layout

### ISSUE THREAD

**Issue by nataliepjlin** [gethugothemes/bookworm-light#18]
Hi, I've searched through the files but still can't find the params and html settings for categories. Does anyone know where they locate? Thanks:)

**Comment by tfsomrat** [comment]
Hello @nataliepjlin 

Which type of settings you are looking for? and the HTML is actually rendering from `layouts/default/list.html` file

**Comment by nataliepjlin** [comment]
@tfsomrat I'm trying to adjust the layout of the categories pages

**Comment by tfsomrat** [comment]
Then your answer is still `layouts/default/list.html` file. is there anything else I can help with?

**Comment by nataliepjlin** [comment]
> Then your answer is still `layouts/default/list.html` file. is there anything else I can help with?
