### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by MalteHueckstaedt** [gethugothemes/bookworm-light#22]
Hello, thank you first for the very beautiful Hugo theme! I really love it very much! Since I want to use the theme for Python and R tutorials, the syntax highlighting is very important for me. I work with R-Studio and unfortunately I don't manage to implement syntax highlighting for R. 

I am very grateful for any help

**Comment by tfsomrat** [comment]
Hello @MalteHueckstaedt 
thanks for choosing our theme, this might help you https://gohugo.io/content-management/syntax-highlighting/

**Comment by MalteHueckstaedt** [comment]
thank you!
