### ISSUE TITLE
Contact form not displaying labels and placeholders

### ISSUE THREAD

**Issue by RohitKumar-200** [gethugothemes/bookworm-light#23]
I cloned this repository and followed these instructions to set up my project.

```
# clone the repository
git clone git@github.com:gethugothemes/bookworm-light.git

# cd in the project directory
$ cd bookworm-light/exampleSite/

# Start local dev server
$ hugo server --themesDir ../..
```
But, when I tried to run this locally, the contact form looks like this, labels and placeholders are not showing up.  
And I have no idea how to fix this.

![image](https://user-images.githubusercontent.com/55583961/170143833-af462921-23d8-4903-a157-ff8d7470103b.png)

Please help me with how to fix this.

**Comment by mehedi-sharif** [comment]
Hello @RohitKumar-200 

Thanks for your concern, this issue has been fixed now. please clone it again. have a good day.
