### ISSUE TITLE
How to enable sidebar ?

### ISSUE THREAD

**Issue by sid-r-singh** [gethugothemes/bookworm-light#3]
I cloned this repo & ran `hugo server --themesDir ../..` in the `exampleSite` directory. I was able to preview the site but could not find the sidebar as shown in the demo.

![image](https://user-images.githubusercontent.com/68782815/130954591-f1e5c9e3-53cb-4699-92f3-19cfed454fe1.png)

How do I enable sidebar ?

**Comment by somratpro** [comment]
Hello @sid-r-singh 

Thanks for your interest in our theme, this feature is only available on our premium version. you can purchase it to get an awesome experience and many more features https://gethugothemes.com/products/bookworm/
