### ISSUE TITLE
i was star hugo server in this theme and then i got error

### ISSUE THREAD

**Issue by Tediace** [gethugothemes/bookworm-light#7]
tart building sites … 
hugo v0.88.1-5BC54738 windows/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
Error: Error building site: TOCSS: failed to transform "style.main.scss" (text/x-scss). Check your Hugo installation; you need the extended version to build SCSS/SASS.

please help me
thank u

**Comment by ghprod** [comment]
Or you can just using config.toml from this repo for your main project

**Comment by Tediace** [comment]
thank u so much
